apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  isCA: true
  commonName: "Root CA"
  secretName: root-ca-secret
  issuerRef:
    name: root-bootstrap
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-issuer
spec:
  ca:
    secretName: root-ca-secret