apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-extension
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops.git
    targetRevision: HEAD
    path: manifests/alloy-extension/eu-central-1-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.1.2
    helm:
      values: |
        alloy:
          configMap:
            create: false
            name: alloy-config
        
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

        configReloader:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

        global:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
