apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.3
    helm:
      values: |
        configs:
          params:
            server:
              insecure: true

        redis-ha:
          enabled: true
          redis:
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                memory: 64Mi

          sentinel:
            resources:
              requests:
                cpu: 100m
                memory: 16Mi
              limits:
                memory: 16Mi
        
          splitBrainDetection:
            resources:
              requests:
                cpu: 50m
                memory: 16Mi
              limits:
                memory: 16Mi
        
          haproxy:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 128Mi

        controller:
          replicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 400m
              memory: 1024Mi
            limits:
              memory: 1024Mi

        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 256Mi

        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 128Mi

        dex:
          enabled: false

        applicationSet:
          replicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 64Mi

        notifications:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-extension
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops.git
    targetRevision: HEAD
    path: manifests/argocd-extension/eu-central-1-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
