apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: 1.17.4
    helm:
      parameters:
        - name: cni.chainingMode
          value: aws-cni
        - name: cni.exclusive
          value: 'false'
        - name: enableIPv4Masquerade
          value: 'false'
        - name: routingMode
          value: native
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
