apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.17.0
    helm:
      parameters:
        - name: provider
          value: aws
        - name: aws.region
          value: eu-central-1
        - name: policy
          value: sync
        - name: txtOwnerId
          value: dev-eu-central-1
        - name: domainFilters[0]
          value: dev.eu-central-1.monke.science
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
