apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://charts.lifecycle.keptn.sh'
    chart: keptn
    targetRevision: 0.11.0
    helm:
      values: |
        commitID: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keptn-system
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true