apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-extension
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops.git
    targetRevision: HEAD
    path: manifests/kgateway-extension/eu-central-1-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
