---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway.crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    chart: kgateway-crds
    targetRevision: v2.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kgateway
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    annotations:
      argocd.argoproj.io/sync-wave: "2"
  spec:
    project: default
    source:
      repoURL: cr.kgateway.dev/kgateway-dev/charts
      chart: kgateway
      targetRevision: v2.0.1
      helm:
        values: |
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 64Mi
          
          securityContext:
           capabilities:
             drop:
             - ALL
           readOnlyRootFilesystem: true
           runAsNonRoot: true
           runAsUser: 1000
    destination:
      server: https://kubernetes.default.svc
      namespace: kgateway-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
