apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 2.11.0
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
          spec:
            auth:
              strategy: anonymous
            external_services:
              prometheus:
                url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
              grafana:
                internal_url: http://kube-prometheus-stack-grafana.monitoring.svc:80
              tracing:
                internal_url: https://jaeger-query.jaeger.svc:16685/jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

