apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 2.11.0
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
          spec:
            auth:
              strategy: anonymous
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

