apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 75.6.1
    helm:
      values: |
        defaultRules:
          create: true
          rules:
            kubeControllerManager: false
            kubeProxy: false
        
        grafana:
          enabled: false
        
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 1Gi
        
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                memory: 32Mi
        
        prometheusOperator:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 64Mi
          prometheusConfigReloader:
            resources:
              requests:
                cpu: 50m
                memory: 16Mi
              limits:
                memory: 16Mi
        
        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 32Mi
        
        kube-state-metrics:
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 32Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true