apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      values: |
        deploymentMode: SimpleScalable
        
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::387105013966:role/monke-eu-central-1-dev-loki"
        
        loki:
          podSecurityContext:
            fsGroup: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
          
          containerSecurityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          
          storage:
            type: s3
            s3:
              region: eu-central-1
            bucketNames:
              chunks: monke-eu-central-1-dev-loki-logs
              ruler: monke-eu-central-1-dev-loki-logs
              admin: monke-eu-central-1-dev-loki-logs
        
          schemaConfig:
            configs:
              - from: 1970-01-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        
          storageConfig:
            tsdb_shipper:
              active_index_directory: /data/tsdb-index
              cache_location: /data/tsdb-cache
        
          query_scheduler:
            max_outstanding_requests_per_tenant: 32768
        
          querier:
            max_concurrent: 16
        
        gateway:
          podSecurityContext:
            fsGroup: 101
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false

        memcached:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 11211
            runAsGroup: 11211
            fsGroup: 11211
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
