apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 27.20.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true