apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reference-service-go
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/monkescience
      chart: helm-charts/reference-service-go
      targetRevision: 0.5.2
      helm:
        valueFiles:
          - $values/manifests/reference-service-go/eu-central-1-dev/values.yaml
    - repoURL: https://github.com/monkescience/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: reference-service-go
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
