apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reference-service-go
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/reference-service-go
    targetRevision: 0.5.0
    path: deployments/overlays/eu-central-1-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: reference-service-go
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
