apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-dashboards.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: apiserver
    files:
      - apiserver.json
  - name: cluster-total
    files:
      - cluster-total.json
  - name: controller-manager
    files:
      - controller-manager.json
  - name: k8s-resources-cluster
    files:
      - k8s-resources-cluster.json
  - name: k8s-resources-namespace
    files:
      - k8s-resources-namespace.json
  - name: k8s-resources-node
    files:
      - k8s-resources-node.json
  - name: k8s-resources-pod
    files:
      - k8s-resources-pod.json
  - name: k8s-resources-workload
    files:
      - k8s-resources-workload.json
  - name: k8s-resources-workloads-namespace
    files:
      - k8s-resources-workloads-namespace.json
  - name: kubelet
    files:
      - kubelet.json
  - name: namespace-by-pod
    files:
      - namespace-by-pod.json
  - name: namespace-by-workload
    files:
      - namespace-by-workload.json
  - name: persistentvolumesusage
    files:
      - persistentvolumesusage.json
  - name: pod-total
    files:
      - pod-total.json
  - name: proxy
    files:
      - proxy.json
  - name: scheduler
    files:
      - scheduler.json
  - name: workload-total
    files:
      - workload-total.json
