apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: alloy
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-public
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: keptn-system
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
  annotations:
    keptn.sh/lifecycle-toolkit: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: reference-service-go
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
  annotations:
    keptn.sh/lifecycle-toolkit: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: keptn-demo
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
  annotations:
    keptn.sh/lifecycle-toolkit: enabled
