apiVersion: v1
kind: Service
metadata:
  name: kgateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  loadBalancerClass: eks.amazonaws.com/nlb
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kgateway
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kgateway
spec:
  gatewayClassName: kgateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.dev.eu-central-1.monke.science"
      tls:
        certificateRefs:
          - name: kgateway-wildcard-domain-tls
      # Optional OAuth filter pseudo-config (adjust for your actual controller)
      # filters:
      #   - type: ExtensionRef
      #     extensionRef:
      #       apiGroup: auth.kgateway.io
      #       kind: OAuthFilter
      #       name: github-oauth
