apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - custom-dashboards.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pod-optimization
    files:
      - pod-optimization.json