apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels:
    app.kubernetes.io/name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-nginx
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - name: hello-nginx
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi