apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lifecycle-operator
  labels:
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/name: lifecycle-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: keptn
      app.kubernetes.io/name: lifecycle-operator
  namespaceSelector:
    matchNames:
      - keptn-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics