apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app.kubernetes.io/name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wireguard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wireguard
    spec:
      containers:
        - name: wireguard
          image: linuxserver/wireguard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 51820
              protocol: UDP
          env:
            - name: SERVERURL
              value: "auto"
            - name: PEERS
              value: "vlutz,blutz"
            - name: PEERDNS
              value: "auto"
            - name: INTERNAL_SUBNET
              value: "10.20.30.1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wireguard-config
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    app.kubernetes.io/name: wireguard
spec:
  type: LoadBalancer
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
  selector:
    app.kubernetes.io/name: wireguard