defaultRules:
  create: true
  rules:
    kubeControllerManager: false
    kubeProxy: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 4Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        memory: 32Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 64Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 50m
        memory: 16Mi
      limits:
        memory: 16Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      memory: 32Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      memory: 32Mi
