apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
    - name: kgateway
      namespace: kgateway-system
  hostnames:
    - argocd.dev.eu-central-1.monke.science
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: argocd-server
          port: 8080