apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node-exporter-dashboards.yaml
  - node_alerts.yaml
  - node_rules.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: node-cluster-rsrc-use
    files:
      - node-cluster-rsrc-use.json
  - name: node-rsrc-use
    files:
      - node-rsrc-use.json
  - name: nodes-aix
    files:
      - nodes-aix.json
  - name: nodes-darwin
    files:
      - nodes-darwin.json
  - name: nodes
    files:
      - nodes.json
