apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false