apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  config:
    auth:
      disable_login_form: 'false'
    auth.anonymous:
      enabled: 'true'
      org_role: Editor
    auth.basic:
      enabled: 'false'
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.prometheus.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: jaeger-datasource
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  datasource:
    name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query.jaeger.svc.cluster.local:16686
    isDefault: false
    jsonData:
      spanBar:
        type: None
    editable: false
