apiVersion: v1
kind: Namespace
metadata:
  annotations:
    keptn.sh/lifecycle-toolkit: enabled
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
    istio.io/dataplane-mode: ambient
  name: reference-service-go
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
  name: reference-service-go
  namespace: reference-service-go
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
  name: reference-service-go
  namespace: reference-service-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: reference-service-go
      app.kubernetes.io/version: 20250621-5bc5e3a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: reference-service-go
        app.kubernetes.io/version: 20250621-5bc5e3a
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: dev
        - name: REGION
          value: eu-central-1
        image: ghcr.io/monkescience/reference-service-go:20250621-5bc5e3a
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        name: reference-service-go
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /status/ready
            port: http
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
  name: reference-service-go
  namespace: reference-service-go
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: reference-service-go
      app.kubernetes.io/version: 20250621-5bc5e3a
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reference-service-go
    app.kubernetes.io/version: 20250621-5bc5e3a
  name: reference-service-go
  namespace: reference-service-go
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reference-service-go
